version: '3.8'  

services:  
  backend:   
    build:
      context: ../CrashGameBackend  
      dockerfile: Dockerfile  
    ports:  
      - "8088:8088"  
      - "8089:8089"  
    environment:  
      - DATABASE_URL=postgres://postgres:password@db:5432/crashgame  
      - GAME_PORT=8088
    networks:  
      - app-network 
    depends_on:  
      - db  

  frontend:    
    build:
      context: ../CrashGameFrontEnd  
      dockerfile: Dockerfile  
    ports:  
      - "3000:3000"  
    environment:  
      - NODE_ENV=production
    networks:  
      - app-network 
    depends_on:  
      - backend  

  db:  
    image: postgres:13  
    environment:  
      POSTGRES_DB: crashgame  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
    ports:  
      - "5432:5432"  
    volumes:  
      - pgdata:/var/lib/postgresql/data  
      
networks:  
  app-network:  
    driver: bridge 
volumes:  
  pgdata: 