const dotenv = require("dotenv");
const fs = require("fs");
if (!fs.existsSync("./.env")) {
  fs.copyFileSync("./.env.example", "./.env");
}
dotenv.config();

module.exports = {
  port: process.env.PORT,
  gamePort: process.env.GAME_PORT,

  database: {
    type: process.env.DB_TYPE,
    host: process.env.DB_HOST,
    name: process.env.DB_NAME,
    user: process.env.DB_USER,
    port: parseInt(process.env.DB_PORT),
    pass: process.env.DB_PASS,
    url : process.env.DATABASE_URL
  },
  redis: {
    host: process.env.REDIS_HOST,
    port: parseInt(process.env.REDIS_PORT),
  },
  api: {
    family: process.env.API_FAMILY,
    endPoint: process.env.ENDPOINT_PATH,
    version: process.env.API_VERSION
  },
  secretKey: process.env.SECRET_KEY,
  waitTime: process.env.WAIT_TIME,
  rtp: process.env.RTP,
  max_turns: process.env.MAX_TURNS,
  currencies: [
    "BTC",
    "ETH",
    "SATS",
    "USDT",
    "BNB",
    "XRP",
    "DOGE",
    "LTC",
    "TRX",
    "BCH",
    "XLM",
    "LINK",
    "DOT",
    "EOS",
    "USDC",
    "DAI",
    "XMR",
    "UNI",
    "BSV",
    "KSM",
    "AAVE",
    "YFI",
    "AMPL",
    "SUSHI",
    "WBTC",
    "SNX",
    "CRO",
    "ATOM",
    "MANA",
    "DASH",
    "BAT",
    "APT",
    "ENJ",
    "CRV",
    "WLD",
    "HNT",
    "FDUSD",
    "SUI",
    "BTCB",
    "ARB",
    "GMX",
    "BTG",
    "RENDER",
    "ALGO",
    "BIGTIME",
    "CFX",
    "ICP",
    "BLUR",
    "STRK",
    "HBAR",
    "PEPE",
    "NANO",
    "CHZ",
    "KAVA",
    "NOT",
    "BOME",
    "THETA",
    "NEXO",
    "TFUEL",
    "ENS",
    "LUNA",
    "TAMA",
    "XEN",
    "RUNE",
    "MOTHER",
    "NEIRO",
    "USDC.e",
    "JOE",
    "RON",
    "WIF",
    "USDT.e",
    "OP",
    "FIL",
    "DGB",
    "GMT",
    "JPEG",
    "ICX",
    "XTZ",
    "GST",
    "WBNB",
    "MAGIC",
    "SAMO",
    "SNACK",
    "ROSE",
    "WAXP",
    "KAIA",
    "CAKE",
    "TWT",
    "KAS",
    "WETH",
    "TON",
    "ZK",
    "CBETH",
    "DJCAT",
    "MOODENG",
    "PYTH",
    "BANANO",
    "DOGS",
    "HMSTR",
    "CATI",
    "JB",
    "LIVE",
    "VTHO",
    "BIT",
    "YGG",
    "GODS",
    "NFT",
    "BUSD",
    "SOL",
    "POL",
    "JST",
    "SUNOLD",
    "IOTX",
    "SHIB",
    "NEAR",
    "ONE",
    "ADA",
    "RVN",
    "WAVES",
    "SAND",
    "TUSD",
    "HEX",
    "AXS",
    "ZIL",
    "AVAX",
    "FTM",
    "ETC",
    "USTC",
    "CELO",
    "VIC",
    "VET",
    "SUNNEW",
    "AMP",
    "DCR",
    "EGLD",
    "NEWBTT",
    "QTUM",
    "APE",
    "PEOPLE"
  ]
};
